# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/clone-0.1.30" = {
      name = "_at_types_slash_clone";
      packageName = "@types/clone";
      version = "0.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/clone/-/clone-0.1.30.tgz";
        sha1 = "e7365648c1b42136a59c7d5040637b3b5c83b614";
      };
    };
    "@types/node-4.2.23" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "4.2.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-4.2.23.tgz";
        sha512 = "U6IchCNLRyswc9p6G6lxWlbE+KwAhZp6mGo6MD2yWpmFomhYmetK+c98OpKyvphNn04CU3aXeJrXdOqbXVTS/w==";
      };
    };
    "@types/node-6.0.118" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "6.0.118";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-6.0.118.tgz";
        sha512 = "N33cKXGSqhOYaPiT4xUGsYlPPDwFtQM/6QxJxuMXA/7BcySW+lkn2yigWP7vfs4daiL/7NJNU6DMCqg5N4B+xQ==";
      };
    };
    "@types/parse5-0.0.31" = {
      name = "_at_types_slash_parse5";
      packageName = "@types/parse5";
      version = "0.0.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse5/-/parse5-0.0.31.tgz";
        sha1 = "e827a493a443b156e1b582a2e4c3bdc0040f2ee7";
      };
    };
    "ansi-escape-sequences-3.0.0" = {
      name = "ansi-escape-sequences";
      packageName = "ansi-escape-sequences";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escape-sequences/-/ansi-escape-sequences-3.0.0.tgz";
        sha1 = "1c18394b6af9b76ff9a63509fa497669fd2ce53e";
      };
    };
    "array-back-1.0.4" = {
      name = "array-back";
      packageName = "array-back";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-1.0.4.tgz";
        sha1 = "644ba7f095f7ffcf7c43b5f0dc39d3c1f03c063b";
      };
    };
    "clone-1.0.4" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.4.tgz";
        sha1 = "da309cc263df15994c688ca902179ca3c7cd7c7e";
      };
    };
    "command-line-args-3.0.5" = {
      name = "command-line-args";
      packageName = "command-line-args";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-args/-/command-line-args-3.0.5.tgz";
        sha1 = "5bd4ad45e7983e5c1344918e40280ee2693c5ac0";
      };
    };
    "command-line-usage-3.0.8" = {
      name = "command-line-usage";
      packageName = "command-line-usage";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-usage/-/command-line-usage-3.0.8.tgz";
        sha1 = "b6a20978c1b383477f5c11a529428b880bfe0f4d";
      };
    };
    "core-js-2.5.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.7.tgz";
        sha512 = "RszJCAxg/PP6uzXVXL6BsxSXx/B05oJAQ2vkJRjyjrEcNVycaqOmNb5OTxZPE3xa5gwZduqza6L9JOCenh/Ecw==";
      };
    };
    "deep-extend-0.4.2" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.2.tgz";
        sha1 = "48b699c27e334bf89f10892be432f6e4c7d34a7f";
      };
    };
    "dom5-1.3.6" = {
      name = "dom5";
      packageName = "dom5";
      version = "1.3.6";
      src = fetchurl {
        url = "http://registry.npmjs.org/dom5/-/dom5-1.3.6.tgz";
        sha1 = "a7088a9fc5f3b08dc9f6eda4c7abaeb241945e0d";
      };
    };
    "feature-detect-es6-1.5.0" = {
      name = "feature-detect-es6";
      packageName = "feature-detect-es6";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/feature-detect-es6/-/feature-detect-es6-1.5.0.tgz";
        sha512 = "DzWPIGzTnfp3/KK1d/YPfmgLqeDju9F2DQYBL35VusgSApcA7XGqVtXfR4ETOOFEzdFJ3J7zh0Gkk011TiA4uQ==";
      };
    };
    "find-replace-1.0.3" = {
      name = "find-replace";
      packageName = "find-replace";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-replace/-/find-replace-1.0.3.tgz";
        sha1 = "b88e7364d2d9c959559f388c66670d6130441fa0";
      };
    };
    "parse5-1.5.1" = {
      name = "parse5";
      packageName = "parse5";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-1.5.1.tgz";
        sha1 = "9b7f3b0de32be78dc2401b17573ccaf0f6f59d94";
      };
    };
    "reduce-flatten-1.0.1" = {
      name = "reduce-flatten";
      packageName = "reduce-flatten";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/reduce-flatten/-/reduce-flatten-1.0.1.tgz";
        sha1 = "258c78efd153ddf93cb561237f61184f3696e327";
      };
    };
    "table-layout-0.3.0" = {
      name = "table-layout";
      packageName = "table-layout";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/table-layout/-/table-layout-0.3.0.tgz";
        sha1 = "6ee20dc483db371b3e5c87f704ed2f7c799d2c9a";
      };
    };
    "test-value-2.1.0" = {
      name = "test-value";
      packageName = "test-value";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/test-value/-/test-value-2.1.0.tgz";
        sha1 = "11da6ff670f3471a73b625ca4f3fdcf7bb748291";
      };
    };
    "typical-2.6.1" = {
      name = "typical";
      packageName = "typical";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-2.6.1.tgz";
        sha1 = "5c080e5d661cbbe38259d2e70a3c7253e873881d";
      };
    };
    "wordwrapjs-2.0.0" = {
      name = "wordwrapjs";
      packageName = "wordwrapjs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrapjs/-/wordwrapjs-2.0.0.tgz";
        sha1 = "ab55f695e6118da93858fdd70c053d1c5e01ac20";
      };
    };
  };
  args = {
    name = "crisper";
    packageName = "crisper";
    version = "2.1.1";
      src = builtins.fetchGit {
        url = "https://github.com/PolymerLabs/crisper.git";
        rev = "eab26dec74ab5ddfda96d846bab757138c76c42f";
      };
    dependencies = [
      sources."@types/clone-0.1.30"
      sources."@types/node-4.2.23"
      (sources."@types/parse5-0.0.31" // {
        dependencies = [
          sources."@types/node-6.0.118"
        ];
      })
      sources."ansi-escape-sequences-3.0.0"
      sources."array-back-1.0.4"
      sources."clone-1.0.4"
      sources."command-line-args-3.0.5"
      sources."command-line-usage-3.0.8"
      sources."core-js-2.5.7"
      sources."deep-extend-0.4.2"
      sources."dom5-1.3.6"
      sources."feature-detect-es6-1.5.0"
      sources."find-replace-1.0.3"
      sources."parse5-1.5.1"
      sources."reduce-flatten-1.0.1"
      sources."table-layout-0.3.0"
      sources."test-value-2.1.0"
      sources."typical-2.6.1"
      sources."wordwrapjs-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Make an HTML file with inline scripts CSP compliant";
      homepage = https://github.com/PolymerLabs/crisper;
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
